name: "\U0001F41E Bug report"
description: Report an issue with Pinia
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!
  - type: textarea
    id: bug-description
    attributes:
      label: Describe the bug
      description: A clear and concise description of what the bug is. If you intend to submit a PR for this issue, tell us in the description. Thanks!
      placeholder: Bug description
    validations:
      required: true
  - type: input
    id: reproduction
    attributes:
      label: Reproduction
      description: "If possible, provide a boiled down editable reproduction using a service like JSFiddle, Codepen, CodeSandbox, or a GitHub repository based on this template: https://github.com/piniajs/bug-report. A failing unit test is even better! Otherwise provide as much information as possible to reproduce the problem. You can find examples of different environments at https://github.com/piniajs?q=example&type=source and use them as a bug reproduction. If no reproduction is provided and the information is not enough to reproduce the problem, we won't be able to give it a look **and the issue will be converted into a question and moved to discussions**."
      placeholder: Reproduction
  - type: markdown
    attributes:
      value: |
        ## by creating an issue you are accepting
        - Follow our [Code of Conduct](https://github.com/vuejs/pinia/blob/v2/.github/CODE_OF_CONDUCT.md)
        - Read the [Contributing Guidelines](https://github.com/vuejs/pinia/blob/v2/.github/CONTRIBUTING.md).
        - Read the [docs](https://pinia.vuejs.org/introduction.html).
        - Check that there isn't [already an issue](https://github.com/vuejs/pinia/issues) that reports the same bug to avoid creating a duplicate.
        - Make sure this is a Pinia issue and not a framework-specific issue. For example, if it's a Vue SFC related bug, it should likely be reported to https://github.com/vuejs/core instead.
        - Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vuejs/pinia/discussions).
        - The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.
  - type: checkboxes
    id: checkboxes
    attributes:
      label: Accept
      options:
        - label: accept
          required: true
